more

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -27,13 +27,14 @@ jobs:
     - name: Test
       run: dotnet test useless-stuff-tests --no-restore --verbosity normal
 
-    - name: Install jq
-      run: sudo apt-get install -y jq
-    
-    - name: Setup, Determine, and Parse Version
+    - name: Determine Version
       if: github.ref == 'refs/heads/main'
-      id: gitversion  # This ID should match what you reference later
+      id: gitversion
       run: |
+        # Update package list and install jq
+        sudo apt-get update
+        sudo apt-get install -y jq || { echo "Failed to install jq"; exit 1; }
+        
         # Setup GitVersion
         dotnet tool install --global GitVersion.Tool --version 5.* || { echo "Failed to install GitVersion"; exit 1; }
         
@@ -52,6 +53,7 @@ jobs:
       shell: bash
 
     - name: Create Tag
+      if: github.ref == 'refs/heads/main'
       run: |
         git config --global user.name "GitHub Actions"
         git config --global user.email "actions@github.com"
